#ifndef KEYBOARD_CODES_H
#define KEYBOARD_CODES_H

#include "Ember.h"

namespace Ember {
	enum class EmberKeyCode {
		Zero = SDL_SCANCODE_0,
		One = SDL_SCANCODE_1,
		Two = SDL_SCANCODE_2,
		Three = SDL_SCANCODE_3,
		Four = SDL_SCANCODE_4,
		Five = SDL_SCANCODE_5,
		Six = SDL_SCANCODE_6,
		Seven = SDL_SCANCODE_7,
		Eight = SDL_SCANCODE_8,
		Nine = SDL_SCANCODE_9,

		A = SDL_SCANCODE_A,
		B = SDL_SCANCODE_B,
		C = SDL_SCANCODE_C,
		D = SDL_SCANCODE_D,
		E = SDL_SCANCODE_E,
		F = SDL_SCANCODE_F,
		G = SDL_SCANCODE_G,
		H = SDL_SCANCODE_H,
		I = SDL_SCANCODE_I,
		J = SDL_SCANCODE_J,
		K = SDL_SCANCODE_K,
		L = SDL_SCANCODE_L,
		M = SDL_SCANCODE_M,
		N = SDL_SCANCODE_N,
		O = SDL_SCANCODE_O,
		P = SDL_SCANCODE_P,
		Q = SDL_SCANCODE_Q,
		R = SDL_SCANCODE_R,
		S = SDL_SCANCODE_S,
		T = SDL_SCANCODE_T,
		U = SDL_SCANCODE_U,
		V = SDL_SCANCODE_V,
		W = SDL_SCANCODE_W,
		X = SDL_SCANCODE_X,
		Y = SDL_SCANCODE_Y,
		Z = SDL_SCANCODE_Z,

		Backspace = SDL_SCANCODE_BACKSPACE,
		Windows = SDL_SCANCODE_COMPUTER,
		Comma = SDL_SCANCODE_COMMA,
		Escape = SDL_SCANCODE_ESCAPE,

		F1 = SDL_SCANCODE_F1,
		F2 = SDL_SCANCODE_F2,
		F3 = SDL_SCANCODE_F3,
		F4 = SDL_SCANCODE_F4,
		F5 = SDL_SCANCODE_F5,
		F6 = SDL_SCANCODE_F6,
		F7 = SDL_SCANCODE_F7,
		F8 = SDL_SCANCODE_F8,
		F9 = SDL_SCANCODE_F9,
		F10 = SDL_SCANCODE_F10,
		F11 = SDL_SCANCODE_F11,
		F12 = SDL_SCANCODE_F12,

		RightShift = SDL_SCANCODE_RSHIFT,
		LeftShift = SDL_SCANCODE_LSHIFT,
		LeftAlt = SDL_SCANCODE_LALT,
		RightAlt = SDL_SCANCODE_RALT,
		LeftCtrl = SDL_SCANCODE_LCTRL,
		RightCtrl = SDL_SCANCODE_RCTRL,
		Return = SDL_SCANCODE_RETURN,
		Tab = SDL_SCANCODE_TAB,
		Cap = SDL_SCANCODE_CAPSLOCK,
		Space = SDL_SCANCODE_SPACE,

		LeftArrow = SDL_SCANCODE_LEFT,
		RightArrow = SDL_SCANCODE_RIGHT,
		UpArrow = SDL_SCANCODE_UP,
		DownArrow = SDL_SCANCODE_DOWN,

		Null = 0
	};
}

#endif // !KEYBOARD_CODES_H
